### ISSUE TITLE
Predicate list does not work when more than one predicate

### ISSUE THREAD

**Issue by pietro-lopes** [KubeJS-Mods/KubeJS#1039]
When using `@e` the first predicate is `Entity::isAlive` and this test pass in all entities.
The subsequent test are virtually ignored

Minecraft condenses a List of predicate with `Util.allOf`, that should be done here before starting the entities loop.

https://github.com/KubeJS-Mods/KubeJS/blob/d7a4173c0c158549ee5c6b5bfaedfb59fb796b16/src/main/java/dev/latvian/mods/kubejs/player/EntityArrayList.java#L124-L140

**Comment by KonSola5** [comment]
The cause of this bug lies in Rhino:

https://github.com/KubeJS-Mods/Rhino/blob/0b5c9848fe03af779155bcca4ba7739cdf1cfa67/src/main/java/dev/latvian/mods/rhino/NativeJavaObject.java#L140-L164

When `filter` is requested:
- `fieldsAndMethods` is `null`, so the first branch isn't taken.
- `filter` is found in custom methods, so this function is returned as a result of a `get` operation.
The actual field/method lookup would occur later, in `members.get(this, name, javaObject, false, cx);`

**Comment by pietro-lopes** [comment]
Seems like you found another issue, because I was using other method
<https://github.com/pietro-lopes/KubeJSTweaks/blob/285a7b361266de9f9002b6362cefae548baa7b0a/run/kubejs/server_scripts/test/main.js#L18>

**Comment by KonSola5** [comment]
Oh, so you were calling `filterSelector` from JS, not `filter`.

**Comment by MaxNeedsSnacks** [comment]
We fixed that, right?

**Comment by KonSola5** [comment]
My PR #1094 did exactly that, now the method that takes multiple predicates is called `filterList` and method that takes one predicate is called `filter` so it has the same semantics as a JS method of the same name. The underlaying issue (Rhino prioritizing JS methods over Java ones) is still not fixed though.

EDIT: Wait, this is a different issue, regarding the semantics of `filterList` itself.
